spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${JDBC_DATABASE_USERNAME:root}
    password: ${JDBC_DATABASE_PASSWORD:AAAaaa011095}
    url: ${JDBC_DATABASE_URL:jdbc:mysql://localhost:3306/Library?serverTimezone=UTC}
    platform: mysql
    initialization-mode: always
    continue-on-error: true

  liquibase:
    enabled: true
    drop-first: false
    change-log: db/changelog/changelog-master.yaml

  jpa:
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
    show-sql: true
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect
    open-in-view: false
    generate-ddl: false

  server:
    port: 8080
